module LabelName where

data LabelName  = Accept
                | Accuracy
                | Apathy
                | Attack
                | Authority
                | Backstabber
                | Blamotage
                | Blank
                | BlueSkies
                | Booch
                | Cancel
                | Confirm
                | Continue
                | Data
                | Debutante
                | Defense
                | Desist
                | Dude
                | Exit
                | EyePoke
                | Fight
                | Fire
                | Grass
                | Greed
                | Grublord
                | Gust
                | Hyphen
                | Ignoloof
                | Incub
                | Item
                | Jack
                | Jeff
                | Larry
                | Leaner
                | Mark
                | MeToo
                | Name
                | No
                | Normal
                | Oaf
                | People
                | Peter
                | PPhone
                | Release
                | Reject
                | Run
                | SandAttack
                | Sell
                | Sergey
                | Slidek
                | Slumlord
                | SomethingElse
                | Speed
                | Spite
                | Status
                | Steve
                | SuckerPunch
                | Supplicant
                | Switch
                | Tackle
                | Talent
                | TheDonald
                | Travis
                | Type
                | Unner
                | Water
                | Weathercock
                | Welcome
                | Winner
                | Wit
                | Yes
                | You
    deriving (Enum, Eq, Ord, Read, Show)
