module ProseName where

data ProseName  = AhYouOnlyHaveOne
                | AllRight
                | AmIDreaming
                | AmIInTheWrong
                | AmNotSurprisedToSee
                | AndDontItFeelGood
                | AndThenThereArePeople
                | ApparentlyThisIsJustA
                | Asked
                | AtRestItOftenSpews
                | AttackMissed
                | BeCarefulInThereYou
                | BooksHowDoYouUse
                | BrutalManIWonderWhy
                | ButFuckItYourDestiny
                | ButItFailed
                | ButPinchYourselfBitchYoure
                | CanIReallyHackIt
                | CatchingPeopleIsBecomingMore 
                | ChooseAPerson
                | ComeBackWhenYouveGot
                | CommaMyFavorite
                | DamnIPickedTheWrong
                | Defeated
                | DontGoIntoTheWifi
                | DontTryToUseYour
                | DoYouRememberYourName
                | Enemy
                | EveryoneHereIsWorkingOn
                | Fell
                | FulfillYourDestinyWithYour
                | FullyHealthyPeopleWontLet
                | GoodFightGoodFight
                | GoodIKnewYoudDo
                | Greatly
                | HadYouFiguredItOut
                | HereYouGo
                | HiAgainIllGiveYou
                | Humiliated
                | IAmJustGettingSwarmed
                | IfIEmulateTheGreats
                | IGuessYouNeedTo
                | IHateDealingWithWild
                | IKnowIveHeardThat
                | ILikeToCatchType
                | IntelligentButSkittishItTends
                | InThisWorldThereAre
                | ItDoesntAffect
                | ItIsBornRichAnd
                | ITookCareOfIt
                | ItsNotVeryEffective
                | ItsAsEffectiveAsYoud
                | ItsSuperEffective
                | IUsedToThinkMy
                | IveBeenWatchingYouAll
                | IWokeUpAndIts
                | JebusYoureOutOfPphones
                | LookAtYouYouLook
                | LookOnTheOtherSide
                | MovePersonWhere
                | MyNameIsWokeI
                | MyParentsArePushingMe
                | MyPeopleWereTooSoft
                | MyPersonWonItsFirst
                | OftenSeenPontificatingInLoud
                | OhHiSorryALittle
                | OhHiAreYouStill
                | OhYouNeedSomeHelp
                | OldPeopleLookAtSome
                | OneMoment
                | PeopleAtAHighLevel
                | PeopleUsePeopleForFights
                | Used
                | ReflectionStaredBackOminously
                | Rose
                | S
                | ShitsOnAnythingToWard
                | SighImTiredOfCatching
                | SignalsGreatOverHere
                | StaredDeepIntoTheDark
                | TechnologyIsIncredibleEverSince
                | TheFactIsWereNot
                | TheGreatestWitchHuntIn
                | TheHeadHonchoAtDitfy
                | TheTopPeopleCatchersDont
                | ThisIsAHugeRack
                | ThisCompanyIsOnHard
                | ThisIsANewOffice
                | ThisIsAWildPlace
                | ThrewAPphone
                | UseItemOnWhichPerson
                | WantToStopMeYou
                | WelcomeToTheWorldOf
                | WelcomeToDitfy
                | WellPoop
                | WeOfferOnSiteWellness
                | WereGonnaSpendAllDay
                | WerePlanningAPeoplethon
                | WeWokeInnovationStation
                | WhatDontGiveMeThat
                | WhatDontLookAtMe
                | WhatTheFuckPeople
                | WhereAmI
                | WhewIveBeenWorkingAll
                | WhoAreYouRunningFrom
                | WildPeopleAreInThere
                | WillNotBeHereTo
                | WowMaybeIllTakeA
                | YouAreNowCrossingThe
                | YouFinallyLostYourMind
                | YoullDoGreatHeadNorth
                | YouLookLikeASmart
                | YourHeadcountIsMeaninglessIf
                | YourPeopleArentReadyFor
                | YourTeamMustBeGetting
    deriving (Enum, Eq, Ord, Read, Show)
