module SpriteName where

data SpriteName = AvatarBack
                | AvatarBackStepLeft
                | AvatarBackStepRight
                | AvatarFront
                | AvatarFrontStepLeft
                | AvatarFrontStepRight
                | AvatarLeft
                | AvatarLeftStep
                | AvatarPortrait
                | AvatarRight
                | AvatarRightStep
                | BattleAvatarBack
                | BlamotageBack
                | BlamotageFront
                | Cursor
                | Donald
                | DonaldBack
                | DonaldBackStepLeft
                | DonaldBackStepRight
                | DonaldFront
                | DonaldFrontStepLeft
                | DonaldFrontStepRight
                | DonaldLeft
                | DonaldLeftStep
                | DonaldRight
                | DonaldRightStep
                | ElectrodeFront
                | Grublord
                | HpBorderMiddle
                | HpBorderSide
                | HpLabel
                | IgnoloofBack
                | IgnoloofFront
                | IncubBack
                | IncubFront
                | KidBack
                | KidBackStepLeft
                | KidBackStepRight
                | KidFront
                | KidFrontStepLeft
                | KidFrontStepRight
                | KidLeft
                | KidLeftStep
                | KidRight
                | KidRightStep
                | Leaner
                | LeanerBack
                | LeanerBackStepLeft
                | LeanerBackStepRight
                | LeanerFront
                | LeanerFrontStepLeft
                | LeanerFrontStepRight
                | LeanerLeft
                | LeanerLeftStep
                | LeanerRight
                | LeanerRightStep
                | LevelLabel
                | Logo
                | ManBack
                | ManBackStepLeft
                | ManBackStepRight
                | ManFront
                | ManFrontStepLeft
                | ManFrontStepRight
                | ManLeft
                | ManLeftStep
                | ManRight
                | ManRightStep
                | MomBack
                | MomBackStepLeft
                | MomBackStepRight
                | MomFront
                | MomFrontStepLeft
                | MomFrontStepRight
                | MomLeft
                | MomLeftStep
                | MomRight
                | MomRightStep
                | PPhone
                | PPhoneFlash1
                | PPhoneFlash2
                | PPhoneFlash3
                | ScrollArrow
                | SlidekBack
                | SlidekFront
                | SparkBig
                | SparkSmall
                | UnnerBack
                | UnnerFront
                | Viacom
                | Wifi
                | Woke
                | WokeBack
                | WokeBackStepLeft
                | WokeBackStepRight
                | WokeFront
                | WokeFrontStepLeft
                | WokeFrontStepRight
                | WokeLeft
                | WokeLeftStep
                | WokeRight
                | WokeRightStep
    deriving (Enum, Eq, Ord, Read, Show)
