module TileName where

data TileName = BedBottomLeft
              | BedBottomMiddle
              | BedBottomRight
              | BedTopLeft
              | BedTopMiddle
              | BedTopRight
              | Bench
              | Blank
              | BookshelfBottom
              | BookshelfTop
              | BuildingBottomWindow
              | BuildingMiddle
              | BuildingMiddleWindow
              | BuildingMiddleWindowTop
              | BuildingRoofMiddle
              | BuildingRoofSide
              | BuildingRoofTopMiddle
              | BuildingRoofTopSide
              | BuildingSide
              | BuildingSign
              | BuildingTopMiddle
              | BuildingTopSide
              | BuildingTopWindow
              | Bush
              | Concrete
              | ConcreteCorner
              | ConcreteE
              | ConcreteN
              | Dirt
              | FloorHardwood
              | FloorHardwoodSeat
              | FloorHardwoodSeatH
              | FloorHardwoodStair
              | Grass
              | HouseplantBottom
              | HouseplantTop
              | HouseBottomMiddle
              | HouseBottomSide
              | HouseBottomWindow
              | HouseDoor
              | HouseRoofMiddle
              | HouseRoofSide
              | HouseRoofTopMiddle
              | HouseRoofTopSide
              | HouseTopMiddle
              | HouseTopSide
              | HouseTopWindow
              | KitchenCounterBottom
              | KitchenCounterTop
              | Ledge
              | LunchTableLeft
              | LunchTableMiddle
              | PhoneRackBottom
              | PhoneRackTop
              | PlanterNE
              | PlanterNW
              | PlanterSE
              | PlanterSW
              | Railing
              | RefrigeratorBottom
              | RefrigeratorTop
              | Rug
              | SofaBottom
              | SofaTop
              | SolidWhite
              | SummaryArrowBack
              | SummaryArrowFront
              | SummaryArrowMiddle
              | StairsAscending
              | StairsDescending
              | TableN
              | TableNW
              | TableS
              | TableSW
              | TableW
              | TextBoxBottomLeft
              | TextBoxBottomMiddle
              | TextBoxBottomRight 
              | TextBoxLeft
              | TextBoxRight
              | TextBoxTopLeft
              | TextBoxTopMiddle
              | TextBoxTopRight
              | WallInterior
              | WindowInterior
    deriving (Enum, Eq, Ord, Read, Show)
